#!/usr/bin/env zsh

quire/apply style/"$1" &&
quire/apply style/adrift proof/adrift.css &&
quire/apply style/burning proof/adrift.css &&
quire/apply style/celestial proof/celestial.css &&
quire/apply style/doctoral proof/doctoral.css
