#!/usr/bin/env sh
# Delete and reapply all styles.

quarto/delete css && quarto/apply style/adrift
quarto/apply style/adrift proof/adrift.css
quarto/apply style/burning proof/burning.css
quarto/apply style/celestial proof/celestial.css
quarto/apply style/doctoral proof/doctoral.css
