#!/usr/bin/env bash

quire/apply style/adrift &&
quire/apply style/adrift proof/adrift.css &&
quire/apply style/burning proof/burning.css &&
quire/apply style/celestial proof/celestial.css &&
quire/apply style/doctoral proof/doctoral.css
