#!/usr/bin/env python3

from argparse import ArgumentParser

from pages import Pages

opt = ArgumentParser()
opt.description = "Build pages from HTML fragments."
arg = opt.add_argument
arg("READY", default="ready", nargs="?", help="Read raw pages from this folder.")
arg("TARGET", default="test", nargs="?", help="Save full pages to this folder.")
opt = opt.parse_args()

print(f"O brave new {opt.TARGET} that has {opt.READY} pages in it!")
Pages(opt.READY).build(opt.TARGET)
print("Exeunt.")
