#!/usr/bin/env python3

from argparse import ArgumentParser

from quire import Quire

opt = ArgumentParser()
opt.description = "Build pages from HTML <main> elements."
arg = opt.add_argument
arg("PAGES", default="ready", nargs="?", help="Read pages from this folder.")
arg("SITE", default="proof", nargs="?", help="Save pages to this folder.")
opt = opt.parse_args()

print(f"O brave new {opt.SITE} that has {opt.PAGES} pages in it!")
Quire(opt.PAGES).build(opt.SITE)
print("Exeunt.")
