#!/usr/bin/env python3

from argparse import ArgumentParser

from quire import Quire

opt = ArgumentParser()
opt.description = "Clean HTML files and extract <body> elements."
arg = opt.add_argument
arg("DIRTY", default="ready", nargs="?", help="Read pages from this folder.")
arg("CLEAN", default="ready", nargs="?", help="Write pages to this folder.")
opt = opt.parse_args()

print(f"This above all: in thine {opt.CLEAN} folder be Tidy.")
Quire.clean(opt.DIRTY,opt.CLEAN)
print("Exeunt.")
