#!/usr/bin/env python3

from argparse import ArgumentParser

from pages import Pages

opt = ArgumentParser()
opt.description = "Delete files with selected suffix recursively."
arg = opt.add_argument
arg("SUFFIX", default=".html", nargs="?", help="Delete files with this suffix.")
arg("TARGET", default="test", nargs="?", help="Delete files from this folder.")
opt = opt.parse_args()

print("Out, {} {}! Out, I say!".format(opt.TARGET, opt.SUFFIX))
Pages.delete(opt.SUFFIX, opt.TARGET)
print("Exeunt.")
