#!/usr/bin/env zsh

tidy \
  --clean yes \
  --doctype html5 \
  --enclose-text yes \
  --indent auto \
  --output-file TEST.html \
  --output-html yes \
  --quiet yes \
  --show-body-only yes \
  --vertical-space no \
  --wrap 80 \
  "$@"
