#!/usr/bin/env python3

from pathlib import Path
from subprocess import run
from sys import stderr

REPO = Path(__file__).resolve().parent.parent
READY = REPO/'ready'

home = REPO/'pages/index.html'
#paths = home.parent.glob('**/*.html')
#paths = (home, *sorted( x for x in paths if x != home ))

inpath = home
outpath = READY / inpath.relative_to(home.parent)

cmds = 'tidy --clean yes --quiet yes --show-warnings yes --show-body-only yes'.split()

print('Save',outpath)
outpath.parent.mkdir(exist_ok=True,parents=True)
with open(outpath,'wb') as file:
    proc = run((*cmds,inpath),check=True,stdout=file)



