#!/usr/bin/env python3

from argparse import ArgumentParser

from pages import Pages

opt = ArgumentParser()
opt.description = "Apply selected style to built pages."
opt.add_argument(
    "STYLE",
    default="style",
    nargs="?",
    help="read CSS from this folder"
)
opt.add_argument(
    "TARGET",
    default="target",
    nargs="?",
    help="save {} to this folder".format(Pages.CSSPATH)
)
opt = opt.parse_args()

print(opt.STYLE, "by any other name would style as sheet.")
Pages.apply(opt.STYLE, opt.TARGET)

print("Exeunt.")
