#!/usr/bin/env python3

from argparse import ArgumentParser

from pages import Pages

opt = ArgumentParser()
opt.description = "Build pages from HTML fragments."
opt.add_argument(
    "READY", default="ready", nargs="?", help="Read raw pages from this folder."
)
opt.add_argument(
    "TARGET", default="target", nargs="?", help="Save finished pages to this folder."
)
opt = opt.parse_args()

print("O brave new", opt.TARGET, "that has", opt.READY, "pages in 't!")
Pages(opt.READY).build(opt.TARGET)
print("Exeunt.")
