#!/usr/bin/env python3

from argparse import ArgumentParser

from quarto import Quarto

opt = ArgumentParser()
opt.description = "Build pages from clean HTML files."
opt.add_argument(
  "READY",
  default="ready",
  nargs="?",
  help="read HTML from this folder"
)
opt.add_argument(
  "TARGET",
  default="target",
  nargs="?",
  help="save HTML to this folder"
)
opt = opt.parse_args()
print("O brave new", opt.TARGET, "that has", opt.READY, "pages in 't!")

Quarto(opt.READY).build(opt.TARGET)
print("Exeunt.")
