#!/usr/bin/env python3

from argparse import ArgumentParser

from pages import Pages

opt = ArgumentParser()
opt.description = "Clean HTML files and extract <body> elements."
opt.add_argument(
    "INPUT",
    default="ready",
    nargs="?",
    help="read dirty HTML files from this folder"
)
opt.add_argument(
    "OUTPUT",
    default="ready",
    nargs="?",
    help="save clean HTML files to this folder"
)
opt = opt.parse_args()

print("This above all: to HTML5 standards be tidy.")
Pages(opt.INPUT).clean(opt.OUTPUT)

print("Exeunt.")
