#!/usr/bin/env python3

from argparse import ArgumentParser

from pages import Pages

opt = ArgumentParser()
opt.description = "Clean HTML files and extract <body> elements."
opt.add_argument(
    "DIRTY", default="ready", nargs="?", help="Read dirty pages from this folder."
)
opt.add_argument(
    "CLEAN", default="ready", nargs="?", help="Save clean pages to this folder."
)
opt = opt.parse_args()

print("This above all: to HTML5 standards be Tidy.")
Pages(opt.DIRTY).clean(opt.CLEAN)
print("Exeunt.")
