#!/usr/bin/env python3

from argparse import ArgumentParser

from quarto import Quarto

opt = ArgumentParser()
opt.description = "Delete files with selected suffix recursively."
opt.add_argument(
    "SUFFIX",
    default=".html",
    nargs="?",
    help="delete files with this extension"
)
opt.add_argument(
    "TARGET",
    default="target",
    nargs="?",
    help="delete from this folder"
)
opt = opt.parse_args()
print("Out, damned", opt.SUFFIX, "! What's done cannot be undone to", opt.TARGET)

Quarto.delete(opt.SUFFIX, opt.TARGET)
print("Exeunt.")
