#!/usr/bin/env zsh
# Extract <body> and save to a file.

outpath='clean.html'

tidy \
  --bare yes \
  --clean yes \
  --gdoc yes \
  --output-file $outpath \
  --output-html yes \
  --quiet yes \
  --show-body-only yes \
  "$@"

echo $?

# --show-warnings yes \
# --show-info yes \
# --quiet yes \
# --doctype html5 \
# --enclose-text yes \
# --indent auto \
# --vertical-space yes \
# --wrap 80 \

